// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var FormData$Phantomtypereason = require("./FormData.bs.js");

console.log("Hello, BuckleScript and Reason!");

var a = FormData$Phantomtypereason.formData("foobar");

var b = FormData$Phantomtypereason.validate(a);

var c = FormData$Phantomtypereason.upperCase(FormData$Phantomtypereason.formData("foobar"));

console.log("formData(unvalidated): ", a);

console.log("option(formData(validated)): ", b);

console.log("upperCase foobar: ", c);

var a$1 = FormData$Phantomtypereason.formData("foobar");

var b$1 = FormData$Phantomtypereason.validate(a$1);

exports.c = c;
exports.a = a$1;
exports.b = b$1;
/*  Not a pure module */
