// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function formData(a) {
  return a;
}

var upperCase = $$String.uppercase_ascii;

function validate(a) {
  if (a.length > 3) {
    return a;
  }
  
}

exports.formData = formData;
exports.upperCase = upperCase;
exports.validate = validate;
/* No side effect */
