// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");

function formData(a) {
  return a;
}

var upperCase = $$String.uppercase_ascii;

function validate(a) {
  if (a.length > 3) {
    return a;
  }
  
}

var $$FormData = {
  formData: formData,
  upperCase: upperCase,
  validate: validate
};

var a = "foobar";

console.log(a);

exports.$$FormData = $$FormData;
exports.a = a;
/*  Not a pure module */
